<a href="https://colab.research.google.com/github/TriDuks/AI/blob/main/Week8_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
from sklearn.linear_model import Perceptron
x = [[0,0],[0,1],[1,0],[1,1]]
t = [0,1,1,1]
model = Perceptron()
model.fit(x,t)
model.score(x,t)
x1 = [[0.5,-1],[0.5,0.5],[-1,1]]
y1 = model.predict(x1)
model.score(x1,y1)


1.0

In [24]:
x1 = [[-0.5, 1],[-0.5, 1],[0.3,0],[-0.1,0]]
x2 = [[-0.5, 1],[0.5, 1],[-0.5,0],[1, 0]]

y1 = model.predict(x1)
print(y1)
model.score(x1, y1)

y2 = model.predict(x2)
print(y2)
model.score(x1, y2)

[0 0 0 0]
[0 1 0 1]


0.5

In [38]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import seaborn as sas 
import numpy as np
iris = datasets.load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [42]:
set(iris)

{'DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names'}

In [ ]:
sas.pairplot(X)

In [48]:
correlation = iris.corr()
print(correlation)

AttributeError: ignored

In [77]:
X = iris.data
y = iris.target
print(x[:5])
print(y[:5]) 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
Sc = StandardScaler()
Sc.fit(X_train)
X_train_Std = Sc.transform(X_train)
X_test_Std = Sc.transform(X_test)
print(X_train)
print(X_train_Std)
X_test_Std.shape

[[0, 0], [0, 1], [1, 0], [1, 1]]
[0 0 0 0 0]
[[6.7 3.  5.  1.7]
 [5.7 4.4 1.5 0.4]
 [6.2 2.8 4.8 1.8]
 [5.1 2.5 3.  1.1]
 [5.1 3.7 1.5 0.4]
 [5.7 3.  4.2 1.2]
 [5.  3.5 1.3 0.3]
 [5.9 3.  4.2 1.5]
 [5.8 2.6 4.  1.2]
 [6.2 2.2 4.5 1.5]
 [4.6 3.6 1.  0.2]
 [6.8 2.8 4.8 1.4]
 [5.  3.3 1.4 0.2]
 [5.1 3.5 1.4 0.3]
 [6.5 3.  5.5 1.8]
 [5.7 2.9 4.2 1.3]
 [5.8 2.7 3.9 1.2]
 [5.5 2.5 4.  1.3]
 [5.  3.4 1.5 0.2]
 [7.7 3.8 6.7 2.2]
 [5.6 3.  4.5 1.5]
 [5.  3.6 1.4 0.2]
 [6.1 2.8 4.7 1.2]
 [7.9 3.8 6.4 2. ]
 [5.  3.4 1.6 0.4]
 [4.4 3.2 1.3 0.2]
 [5.7 3.8 1.7 0.3]
 [4.4 3.  1.3 0.2]
 [6.7 3.1 4.4 1.4]
 [6.7 3.1 4.7 1.5]
 [6.8 3.  5.5 2.1]
 [5.2 3.5 1.5 0.2]
 [4.9 3.1 1.5 0.1]
 [6.7 3.3 5.7 2.5]
 [4.9 3.6 1.4 0.1]
 [6.  3.4 4.5 1.6]
 [4.6 3.1 1.5 0.2]
 [5.  3.  1.6 0.2]
 [6.7 2.5 5.8 1.8]
 [6.7 3.1 5.6 2.4]
 [4.6 3.4 1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [5.1 3.8 1.5 0.3]
 [6.1 2.9 4.7 1.4]
 [6.4 3.2 5.3 2.3]
 [5.1 3.5 1.4 0.2]
 [5.2 3.4 1.4 0.2]
 [4.5 2.3 1.3 0.3]
 [5.4 3.  4.5 1.5]
 [4.7 3.2 1.6 0.2]
 [5.9

(45, 4)

In [86]:
model = Perceptron( max_iter=40, eta0=  0.1, random_state=0)
model.fit(X_train_Std,y_train)
y_pred = model.predict(X_test_Std)
z_pred = model.predict(X_train_Std)

print(y_pred)
print('Độ chính xác của mô hình: ', accuracy_score(y_test,y_pred))



[2 0 2 1 0 2 2 0 2 2 1 0 1 2 2 1 2 2 1 1 2 0 1 2 2 0 0 0 2 0 2 0 2 0 2 2 2
 1 0 0 2 1 2 2 0]
Độ chính xác của mô hình:  0.7777777777777778


In [ ]:
y_test_Std = Sc.transform(y_test)
y_train_Std = Sc.transform(y_train)

In [72]:
from sklearn.linear_model import LinearRegression
import pandas as pd
Regression = LinearRegression()
Regression.fit(X_train,y_train)
y_pred = Regression.predict(X_test).round(1)
calcumaion = pd.DataFrame(np.c_[y_test,y_pred])

print('Độ chính xác của mô hình')
print(Regression.score(X_train,y_train))
print(Regression.score(X_test,y_test))

Độ chính xác của mô hình
0.9212412404643604
0.9465494660340679
